{% set name = "bw2calc" %}
{% set version = "2.0.dev17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea55a4f32b3f6815fb5af9bce623f1fc51042c2194d686a3c191d3871fe52a17

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - bw_processing >=0.9.5
    - json-logging
    - matrix_utils >=0.4.3
    - numpy <2
    - pandas
    - pydantic
    - scipy
    - stats_arrays
    - pypardiso  # [not (osx and arm64)]
    - scikit-umfpack  # [osx and arm64]

test:
  imports:
    - bw2calc

about:
  home: https://github.com/brightway-lca/brightway2-calc
  summary: 'The calculation engine for the Brightway life cycle assessment framework.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/brightway-lca/brightway2-calc

extra:
  recipe-maintainers:
    - michaelweinold
    - cmutel
    - m-rossi
